// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TrumaDisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void j_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_TrumaMainScreen
void ui_TrumaMainScreen_screen_init(void);
lv_obj_t * ui_TrumaMainScreen;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Temp;
void ui_event_Heating(lv_event_t * e);
lv_obj_t * ui_Heating;
void ui_event_Boiler(lv_event_t * e);
lv_obj_t * ui_Boiler;
void ui_event_Fan(lv_event_t * e);
lv_obj_t * ui_Fan;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_RoomTemp;
lv_obj_t * ui_WaterTemp;
lv_obj_t * ui_Voltage;
lv_obj_t * ui_Waterboost;
void ui_event_ResetButton(lv_event_t * e);
lv_obj_t * ui_ResetButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_ErrClass;
lv_obj_t * ui_ErrCode;
lv_obj_t * ui_RoomDemand;
lv_obj_t * ui_WaterDemand;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Window;
lv_obj_t * ui_ScreenOff;


// SCREEN: ui_ErrorScreen
void ui_ErrorScreen_screen_init(void);
lv_obj_t * ui_ErrorScreen;
lv_obj_t * ui_ErrorLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void j_Animation(lv_obj_t * TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Heating(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        HeatingOn(e);
    }
}
void ui_event_Boiler(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        WaterChanged(e);
    }
}
void ui_event_Fan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FanChanged(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        DecrTemperature(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        DecrTemperature(e);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        IncrTemperature(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        IncrTemperature(e);
    }
}
void ui_event_ResetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ResetError(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_TrumaMainScreen_screen_init();
    ui_ErrorScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_TrumaMainScreen);
}
