// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: TrumaDisplay

#ifndef _TRUMADISPLAY_UI_H
#define _TRUMADISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void j_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_TrumaMainScreen
void ui_TrumaMainScreen_screen_init(void);
extern lv_obj_t * ui_TrumaMainScreen;
extern lv_obj_t * ui_Label1;
void ui_event_Heating(lv_event_t * e);
extern lv_obj_t * ui_Heating;
void ui_event_Boiler(lv_event_t * e);
extern lv_obj_t * ui_Boiler;
void ui_event_Fan(lv_event_t * e);
extern lv_obj_t * ui_Fan;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_btnDecrement(lv_event_t * e);
extern lv_obj_t * ui_btnDecrement;
extern lv_obj_t * ui_Label5;
void ui_event_btnIncrement(lv_event_t * e);
extern lv_obj_t * ui_btnIncrement;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_RoomTemp;
extern lv_obj_t * ui_WaterTemp;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_Waterboost;
void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ErrClass;
extern lv_obj_t * ui_ErrCode;
extern lv_obj_t * ui_RoomDemand;
extern lv_obj_t * ui_WaterDemand;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Window;
extern lv_obj_t * ui_ScreenOff;
void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
void ui_event_Temp(lv_event_t * e);
extern lv_obj_t * ui_Temp;
// CUSTOM VARIABLES

// SCREEN: ui_ErrorScreen
void ui_ErrorScreen_screen_init(void);
extern lv_obj_t * ui_ErrorScreen;
extern lv_obj_t * ui_ErrorLabel;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Roboto);
LV_FONT_DECLARE(ui_font_Roboto38);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
