// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TrumaDisplay

#ifndef _TRUMADISPLAY_UI_H
#define _TRUMADISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void j_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_TrumaMainScreen
void ui_TrumaMainScreen_screen_init(void);
extern lv_obj_t * ui_TrumaMainScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Temp;
void ui_event_Heating(lv_event_t * e);
extern lv_obj_t * ui_Heating;
void ui_event_Boiler(lv_event_t * e);
extern lv_obj_t * ui_Boiler;
void ui_event_Fan(lv_event_t * e);
extern lv_obj_t * ui_Fan;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_RoomTemp;
extern lv_obj_t * ui_WaterTemp;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_Waterboost;
void ui_event_ResetButton(lv_event_t * e);
extern lv_obj_t * ui_ResetButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ErrClass;
extern lv_obj_t * ui_ErrCode;
extern lv_obj_t * ui_RoomDemand;
extern lv_obj_t * ui_WaterDemand;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Window;
extern lv_obj_t * ui_ScreenOff;
// SCREEN: ui_ErrorScreen
void ui_ErrorScreen_screen_init(void);
extern lv_obj_t * ui_ErrorScreen;
extern lv_obj_t * ui_ErrorLabel;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_Roboto);
LV_FONT_DECLARE(ui_font_Roboto38);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
