// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: TrumaDisplay

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void HeatingOn(lv_event_t * e);
void WaterChanged(lv_event_t * e);
void FanChanged(lv_event_t * e);
void DecrTemperature(lv_event_t * e);
void IncrTemperature(lv_event_t * e);
void ResetError(lv_event_t * e);
void KeyboardClick(lv_event_t * e);
void TemperatureClick(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
