// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TrumaDisplay

#include "ui.h"

void ui_ErrorScreen_screen_init(void)
{
    ui_ErrorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ErrorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ErrorLabel = lv_label_create(ui_ErrorScreen);
    lv_obj_set_width(ui_ErrorLabel, lv_pct(100));
    lv_obj_set_height(ui_ErrorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ErrorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorLabel, "Error");
    lv_obj_set_style_text_color(ui_ErrorLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ErrorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrorLabel, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

}
