// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: TrumaDisplay

#include "ui.h"

void ui_TrumaMainScreen_screen_init(void)
{
    ui_TrumaMainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TrumaMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TrumaMainScreen, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TrumaMainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TrumaMainScreen, lv_color_hex(0x29FFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TrumaMainScreen, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label1, "Calefacción");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Heating = lv_switch_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Heating, 50);
    lv_obj_set_height(ui_Heating, 24);
    lv_obj_set_x(ui_Heating, 40);
    lv_obj_set_y(ui_Heating, 61);
    lv_obj_set_style_bg_color(ui_Heating, lv_color_hex(0x0F97F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Heating, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Boiler = lv_dropdown_create(ui_TrumaMainScreen);
    lv_dropdown_set_options(ui_Boiler, "Off\nEco\nHigh\nBoost");
    lv_obj_set_width(ui_Boiler, 75);
    lv_obj_set_height(ui_Boiler, 40);
    lv_obj_set_x(ui_Boiler, 141);
    lv_obj_set_y(ui_Boiler, 20);
    lv_obj_add_flag(ui_Boiler, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Boiler, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Boiler, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Boiler), &ui_font_Roboto,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Boiler), &ui_font_Roboto,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Fan = lv_dropdown_create(ui_TrumaMainScreen);
    lv_dropdown_set_options(ui_Fan, "Eco\nHigh\nOff\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10");
    lv_obj_set_width(ui_Fan, 77);
    lv_obj_set_height(ui_Fan, 40);
    lv_obj_set_x(ui_Fan, 228);
    lv_obj_set_y(ui_Fan, 20);
    lv_obj_add_flag(ui_Fan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Fan, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Fan, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_Fan, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_color(ui_Fan, lv_color_hex(0xB4B6B4), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Fan, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_text_font(ui_Fan, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Fan), &ui_font_Roboto,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Fan), &ui_font_Roboto,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 146);
    lv_obj_set_y(ui_Label3, 0);
    lv_label_set_text(ui_Label3, "Agua");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 234);
    lv_obj_set_y(ui_Label4, 0);
    lv_label_set_text(ui_Label4, "Ventilador");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDecrement = lv_btn_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_btnDecrement, 35);
    lv_obj_set_height(ui_btnDecrement, 40);
    lv_obj_set_x(ui_btnDecrement, 0);
    lv_obj_set_y(ui_btnDecrement, 20);
    lv_obj_add_flag(ui_btnDecrement, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDecrement, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_btnDecrement);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "-");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnIncrement = lv_btn_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_btnIncrement, 35);
    lv_obj_set_height(ui_btnIncrement, 40);
    lv_obj_set_x(ui_btnIncrement, 96);
    lv_obj_set_y(ui_btnIncrement, 20);
    lv_obj_add_flag(ui_btnIncrement, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnIncrement, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_btnIncrement);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 5);
    lv_obj_set_y(ui_Label7, 89);
    lv_label_set_text(ui_Label7, "Temperatura ºC");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 144);
    lv_obj_set_y(ui_Label8, 89);
    lv_label_set_text(ui_Label8, "Agua ºC");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 233);
    lv_obj_set_y(ui_Label9, 89);
    lv_label_set_text(ui_Label9, "Tensión V");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomTemp = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_RoomTemp, 90);
    lv_obj_set_height(ui_RoomTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RoomTemp, 13);
    lv_obj_set_y(ui_RoomTemp, 109);
    lv_label_set_long_mode(ui_RoomTemp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_RoomTemp, "--");
    lv_obj_set_style_text_align(ui_RoomTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RoomTemp, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WaterTemp = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_WaterTemp, 90);
    lv_obj_set_height(ui_WaterTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WaterTemp, 119);
    lv_obj_set_y(ui_WaterTemp, 109);
    lv_label_set_long_mode(ui_WaterTemp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_WaterTemp, "--");
    lv_obj_set_style_text_align(ui_WaterTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WaterTemp, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voltage = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Voltage, 90);
    lv_obj_set_height(ui_Voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Voltage, 217);
    lv_obj_set_y(ui_Voltage, 109);
    lv_label_set_long_mode(ui_Voltage, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Voltage, "--");
    lv_obj_set_style_text_align(ui_Voltage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Voltage, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Waterboost = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Waterboost, lv_pct(100));
    lv_obj_set_height(ui_Waterboost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Waterboost, 0);
    lv_obj_set_y(ui_Waterboost, -3);
    lv_obj_set_align(ui_Waterboost, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_Waterboost, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Waterboost, "waterboost");
    lv_obj_set_style_text_align(ui_Waterboost, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Waterboost, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetButton = lv_btn_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_ResetButton, 100);
    lv_obj_set_height(ui_ResetButton, 30);
    lv_obj_set_x(ui_ResetButton, -5);
    lv_obj_set_y(ui_ResetButton, -27);
    lv_obj_set_align(ui_ResetButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ResetButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Reset");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrClass = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_ErrClass, 40);
    lv_obj_set_height(ui_ErrClass, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrClass, 2);
    lv_obj_set_y(ui_ErrClass, -19);
    lv_obj_set_align(ui_ErrClass, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_ErrClass, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ErrClass, "W");
    lv_obj_set_style_text_color(ui_ErrClass, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrClass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrClass, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrCode = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_ErrCode, 114);
    lv_obj_set_height(ui_ErrCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrCode, 52);
    lv_obj_set_y(ui_ErrCode, -19);
    lv_obj_set_align(ui_ErrCode, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_ErrCode, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_ErrCode, "255");
    lv_obj_set_style_text_color(ui_ErrCode, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrCode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrCode, &ui_font_Roboto38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RoomDemand = lv_spinner_create(ui_TrumaMainScreen, 1000, 90);
    lv_obj_set_width(ui_RoomDemand, 20);
    lv_obj_set_height(ui_RoomDemand, 20);
    lv_obj_set_x(ui_RoomDemand, 113);
    lv_obj_set_y(ui_RoomDemand, 85);
    lv_obj_clear_flag(ui_RoomDemand, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_border_color(ui_RoomDemand, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RoomDemand, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RoomDemand, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RoomDemand, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RoomDemand, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RoomDemand, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RoomDemand, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_WaterDemand = lv_spinner_create(ui_TrumaMainScreen, 1000, 90);
    lv_obj_set_width(ui_WaterDemand, 20);
    lv_obj_set_height(ui_WaterDemand, 20);
    lv_obj_set_x(ui_WaterDemand, 201);
    lv_obj_set_y(ui_WaterDemand, 85);
    lv_obj_clear_flag(ui_WaterDemand, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_WaterDemand, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterDemand, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_WaterDemand, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WaterDemand, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WaterDemand, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 4);
    lv_obj_set_y(ui_Label10, 159);
    lv_label_set_text(ui_Label10, "Ventana:");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Window = lv_label_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Window, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Window, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Window, 65);
    lv_obj_set_y(ui_Window, 159);
    lv_label_set_text(ui_Window, "---");
    lv_obj_set_style_text_font(ui_Window, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenOff = lv_checkbox_create(ui_TrumaMainScreen);
    lv_checkbox_set_text(ui_ScreenOff, "Apagar pantalla inactiva");
    lv_obj_set_height(ui_ScreenOff, 22);
    lv_obj_set_width(ui_ScreenOff, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_ScreenOff, -7);
    lv_obj_set_y(ui_ScreenOff, 157);
    lv_obj_set_align(ui_ScreenOff, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_state(ui_ScreenOff, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ScreenOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_ScreenOff, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_TrumaMainScreen);
    lv_keyboard_set_mode(ui_Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard, 306);
    lv_obj_set_height(ui_Keyboard, 167);
    lv_obj_set_x(ui_Keyboard, -2);
    lv_obj_set_y(ui_Keyboard, -9);
    lv_obj_add_flag(ui_Keyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Keyboard, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags

    ui_Temp = lv_textarea_create(ui_TrumaMainScreen);
    lv_obj_set_width(ui_Temp, 49);
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Temp, 42);
    lv_obj_set_y(ui_Temp, 20);
    lv_textarea_set_max_length(ui_Temp, 4);
    lv_textarea_set_text(ui_Temp, "5.0");
    lv_textarea_set_one_line(ui_Temp, true);
    lv_obj_clear_flag(ui_Temp, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Temp, &ui_font_Roboto, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_Heating, ui_event_Heating, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Boiler, ui_event_Boiler, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Fan, ui_event_Fan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnDecrement, ui_event_btnDecrement, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnIncrement, ui_event_btnIncrement, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetButton, ui_event_ResetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard, ui_event_Keyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp, ui_event_Temp, LV_EVENT_ALL, NULL);

}
