String ErrText[] {
/*0*/   "",
/*1*/   "",
/*2*/   "",
/*3*/   "",
/*4*/   "",
/*5*/   "",
/*6*/   "",
/*7*/   "",
/*8*/   "",
/*9*/   "",
/*10*/   "Fallo del suministro de tensión de 12 V (sobretensión)",
/*11*/   "Fallo del suministro de tensión de 12 V (baja tensión)",
/*12*/   "",
/*13*/   "",
/*14*/   "",
/*15*/   "",
/*16*/   "",
/*17*/   "Sobrecalentamiento, umbral de hardware excedido",
/*18*/   "La bujía incandescente tiene un consumo de energía demasiado bajo",
/*19*/   "La bujía incandescente tiene un consumo de energía demasiado bajo",
/*20*/   "Interrupción en la bujía incandescente",
/*21*/   "Consumo de corriente de la bujía incandescente demasiado alto",
/*22*/   "Cortocircuito en la bujía incandescente o en el dispositivo de mando Combi D",
/*23*/   "",
/*24*/   "",
/*25*/   "No hay comunicación entre el dispositivo de mando de Combi D y el sistema electrónico de Truma",
/*26*/   "",
/*27*/   "",
/*28*/   "",
/*29*/   "",
/*30*/   "Motor de aire de combustión en el quemador fuera de tolerancia",
/*31*/   "Interrupción en el motor de aire de combustión del quemador",
/*32*/   "Cortocircuito en el motor de aire de combustión del quemador",
/*33*/   "",
/*34*/   "Cortocircuito a tierra en el motor de aire de combustión en el quemador o error del transistor",
/*35*/   "",
/*36*/   "",
/*37*/   "",
/*38*/   "",
/*39*/   "",
/*40*/   "",
/*41*/   "",
/*42*/   "",
/*43*/   "",
/*44*/   "",
/*45*/   "",
/*46*/   "",
/*47*/   "Cortocircuito en la bomba dosificadora",
/*48*/   "Interrupción en la bomba dosificadora- El interruptor de temperatura del agua, el interruptor de temperatura del aire o el conmutador de sobrecalentamiento se han activado",
/*49*/   "Cortocircuito en la bomba dosificadora o en el dispositivo de mando de Combi D",
/*50*/   "Bloqueo del dispositivo de mando de Combi D al encenderse 15 veces seguidas sin detección de la llama",
/*51*/   "Superación del tiempo durante el enfriamiento de la sonda de monitorización de la llama antes del arranque",
/*52*/   "Superación del tiempo de seguridad",
/*53*/   "",
/*54*/   "Interrupción de la llama en la etapa del quemador de 4 kW o suministro insuficiente de combustible",
/*55*/   "",
/*56*/   "Interrupción de la llama en la etapa del quemador de 2 kW o suministro insuficiente de combustible",
/*57*/   "",
/*58*/   "",
/*59*/   "",
/*60*/   "Potencial de tensión incorrecto en el PIN X7 (interrupción)",
/*61*/   "Potencial de tensión incorrecto en el PIN X7 (cortocircuito)",
/*62*/   "",
/*63*/   "",
/*64*/   "Interrupción en el sensor de llama",
/*65*/   "Cortocircuito en la sonda de monitorización de la llama",
/*66*/   "",
/*67*/   "",
/*68*/   "",
/*69*/   "",
/*70*/   "",
/*71*/   "",
/*72*/   "",
/*73*/   "",
/*74*/   "Bloqueo de funcionamiento del dispositivo de mando Combi D, hardware para la detección de sobrecalentamiento defectuoso",
/*75*/   "",
/*76*/   "",
/*77*/   "",
/*78*/   "",
/*79*/   "",
/*80*/   "",
/*81*/   "",
/*82*/   "",
/*83*/   "",
/*84*/   "",
/*85*/   "",
/*86*/   "",
/*87*/   "",
/*88*/   "",
/*89*/   "",
/*90*/   "Error en el dispositivo de mando Combi D",
/*91*/   "Componentes de tensión alterna o interrupciones breves en la tensión de suministro",
/*92*/   "Error en el dispositivo de mando Combi D",
/*93*/   "Error en el dispositivo de mando Combi D",
/*94*/   "Bloqueo de funcionamiento del dispositivo de mando Combi D debido a fallos de transistor o cortocircuitos demasiado frecuentes",
/*95*/   "Error en el dispositivo de mando Combi D",
/*96*/   "Bloqueo de funcionamiento del dispositivo de mando Combi D, sin secuencia de software válida",
/*97*/   "Error en el dispositivo de mando Combi D",
/*98*/   "Error en el dispositivo de mando Combi D",
/*99*/   "Error en el dispositivo de mando Combi D",
/*100*/   "Consumo de corriente del motor de aire de circulación demasiado alto",
/*101*/   "Consumo de corriente del motor de aire de circulación demasiado bajo",
/*102*/   "No hay contacto en el conector del motor o motor de aire de circulación defectuoso",
/*103*/   "",
/*104*/   "",
/*105*/   "",
/*106*/   "",
/*107*/   "",
/*108*/   "",
/*109*/   "",
/*110*/   "Los ajustes en la unidad de mando no se transmiten correctamente",
/*111*/   "Sensor de temperatura ambiente fuera de tolerancia",
/*112*/   "Sensor de temperatura del agua fuera de tolerancia",
/*113*/   "Sensor de temperatura del aire fuera de tolerancia",
/*114*/   "",
/*115*/   "",
/*116*/   "",
/*117*/   "",
/*118*/   "",
/*119*/   "",
/*120*/   "El dispositivo de mando de Combi D no es detectado por el sistema electrónico de Truma",
/*121*/   "Interrupción en la bomba dosificadora- El interruptor de temperatura del agua, el interruptor de temperatura del aire o el conmutador de sobrecalentamiento se han activado",
/*122*/   "El dispositivo de mando de la Combi D comunica un error al sistema electrónico de Truma",
/*123*/   "Se detecta llama aunque no haya ninguna llama encendida",
/*124*/   "",
/*125*/   "",
/*126*/   "",
/*127*/   "",
/*128*/   "",
/*129*/   "",
/*130*/   "Suministro de tensión de 12 V defectuoso / Cortocircuito en el elemento de calefacción FrostControl o en el cable / Cortocircuito en el reloj temporizador o en el cable de conexión de ZUCB",
/*131*/   "Los ajustes en la unidad de mando no se transmiten correctamente",
/*132*/   "Error en el sistema electrónico de Truma",
/*133*/   "Cortocircuito en el motor de aire de combustión en la chimenea de pared o en el cable.",
/*134*/   "Cortocircuito o contacto flojo en un componente externo",
/*135*/   "",
/*136*/   "",
/*137*/   "",
/*138*/   "",
/*139*/   "",
/*140*/   "Velocidad del motor de aire de combustión en la chimenea de pared demasiado baja",
/*141*/   "Simulación de la velocidad del motor de aire de combustión en la chimenea de pared",
/*142*/   "Velocidad del motor de aire de combustión en la chimenea de pared inverosímilmente alta",
/*143*/   "",
/*144*/   "",
/*145*/   "",
/*146*/   "",
/*147*/   "",
/*148*/   "",
/*149*/   "",
/*150*/   "Advertencia de sobretemperatura del aire",
/*151*/   "Advertencia de sobretemperatura del agua",
/*152*/   "El sensor de temperatura del agua indica sobretemperatura en el funcionamiento de agua caliente",
/*153*/   "",
/*154*/   "",
/*155*/   "",
/*156*/   "",
/*157*/   "",
/*158*/   "",
/*159*/   "",
/*160*/   "Fallo del suministro de tensión de 12 V (baja tensión)",
/*161*/   "Fallo del suministro de tensión de 12 V (sobretensión)",
/*162*/   "El conmutador de ventana detecta una ventana abierta o el puente de cables para el conmutador de ventana en el sistema electrónico de Truma está interrumpido",
/*163*/   "Se ha abierto el interruptor de temperatura del aire, el interruptor de temperatura del agua o el conmutador de sobrecalentamiento",
/*164*/   "",
/*165*/   "",
/*166*/   "",
/*167*/   "",
/*168*/   "",
/*169*/   "",
/*170*/   "Riesgo de baja tensión < 11,5 V",
/*171*/   "",
/*172*/   "",
/*173*/   "",
/*174*/   "",
/*175*/   "",
/*176*/   "",
/*177*/   "",
/*178*/   "",
/*179*/   "",
/*180*/   "El sistema electrónico de Truma no se corresponde con la calefacción, la llave electrónica es incorrecta o está disponible",
/*181*/   "",
/*182*/   "",
/*183*/   "",
/*184*/   "",
/*185*/   "",
/*186*/   "",
/*187*/   "",
/*188*/   "",
/*189*/   "",
/*190*/   "",
/*191*/   "",
/*192*/   "",
/*193*/   "",
/*194*/   "",
/*195*/   "",
/*196*/   "",
/*197*/   "",
/*198*/   "",
/*199*/   "",
/*200*/   "",
/*201*/   "",
/*202*/   "",
/*203*/   "",
/*204*/   "",
/*205*/   "",
/*206*/   "",
/*207*/   "",
/*208*/   "",
/*209*/   "",
/*210*/   "",
/*211*/   "",
/*212*/   "",
/*213*/   "",
/*214*/   "",
/*215*/   "",
/*216*/   "",
/*217*/   "",
/*218*/   "",
/*219*/   "",
/*220*/   "",
/*221*/   "",
/*222*/   "",
/*223*/   "",
/*224*/   "",
/*225*/   "",
/*226*/   "",
/*227*/   "",
/*228*/   "",
/*229*/   "",
/*230*/   "",
/*231*/   "",
/*232*/   "",
/*233*/   "",
/*234*/   "",
/*235*/   "",
/*236*/   "",
/*237*/   "",
/*238*/   "",
/*239*/   "",
/*240*/   "",
/*241*/   "",
/*242*/   "",
/*243*/   "",
/*244*/   "",
/*245*/   "",
/*246*/   "",
/*247*/   "",
/*248*/   "",
/*249*/   "",
/*250*/   "",
/*251*/   "",
/*252*/   "",
/*253*/   "",
/*254*/   "",
/*255*/   "Bloqueo de funcionamiento del sistema electrónico de Truma debido a sobrecalentamiento"};
